### ISSUE TITLE
LED Control

### ISSUE THREAD

**Issue by guilyx** [nicofilliol/AMazeBot#3]
Hey, can you push the LED control thing you did on the last arduino lab two or three weeks ago ?

Need a visual confirmation of established com between Mega and RPi :+1:

**Comment by nicofilliol** [comment]
Can't find the file anymore, but was this library: https://github.com/FastLED/FastLED
You can install from within the Arduino IDE though (Sketch < include libraries < manage libraries), and use AnalogOutput file (File < Examples < FastLED) as an example on how to use.

**Comment by guilyx** [comment]
@JanTiepelt 
If you wanna do the LED thing that turns on when communication with raspberry is established, could be cool.
Dont know if it has to be done on the Arduino side or on the ROS Driver side, if its on the Arduino side then its all yours

**Comment by nicofilliol** [comment]
added in commit https://github.com/nicofilliol/AMazeBot/commit/7b93f429d1075c6d5fa3231043d7fe14bba7d8b7
